[package]
name = "http-axum"
version = "0.1.0"
edition = "2021"

[dependencies]
async-stripe = { version = "0.34.1", features = ["runtime-tokio-hyper"] }
axum = "0.7"
lambda_http = "0.11.1"
lambda_runtime = "0.11.1"
serde = "1.0.196"
serde_json = "1.0"
tokio = { version = "1", features = ["macros"] }
