[package]
name = "accept-payments"
version = "0.1.0"
edition = "2021"

[dependencies]
async-stripe = { version = "0.34.1", features = ["runtime-tokio-hyper"] }
axum = "0.7"
lambda_http = "0.11.1"
lambda_runtime = "0.11.1"
openssl = { version = "0.10", features = ["vendored"] }
serde = "1.0.196"
serde_json = "1.0"
tokio = { version = "1", features = ["macros"] }

[profile.release]
strip = false
lto = "fat"
codegen-units = 16
panic = "unwind"
